FROM docker.io/debian:latest

# Variables recommended for Debian Container image
# Recommended below
# github.com/phusion/baseimage-docker/issues/319#issuecomment-1066174043
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS="yes"

# Update the OS
RUN apt-get update > /dev/null

# Install python3
RUN apt-get install python3 -y > /dev/null
RUN apt-get install python3-pip -y > /dev/null
RUN apt-get install python3-virtualenv -y > /dev/null
RUN apt-get install pipx -y > /dev/null

# Symlink python3 to python
RUN apt-get install python-is-python3 -y > /dev/null

# Install curl. Needed to install nvm
RUN apt-get install curl -y > /dev/null

# Install the fish shell
RUN apt-get install fish -y > /dev/null

# Install Git 
RUN apt-get install git -y > /dev/null

# Install direnv
RUN apt-get install direnv -y > /dev/null 

# Install systemctl 
RUN apt-get install systemd -y > /dev/null

# Install sudo
RUN apt-get install sudo -y > /dev/null

# Install nodejs & npm
RUN apt-get install nodejs -y > /dev/null
RUN apt-get install npm -y > /dev/null

# Install prettier globally
RUN npm install -g prettier > /dev/null

# Name of the user within the container
ENV USER devcontainer

# Create a user account for python 3 development
# --home Specifies the user's home directory 
# --shell Specifies the shell that will assigned to the user on login 
# --disabled-password Don't assign a password when creating a user
# --gecos Skip the questionnaire.
RUN adduser \
--home "/home/${USER}" \
--shell "/bin/bash" \
--disabled-password \
--gecos "" \
"${USER}" > /dev/null

# Set a password for the user
RUN echo "${USER}:devcontainer" | chpasswd

# Add the user to the sudo group
RUN adduser "${USER}" sudo > /dev/null

# Allow the user to run sudo without a password
RUN echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Switch to the new user 
USER "${USER}"
WORKDIR "/home/${USER}"

# Create the XDG_BIN_HOME directory
ENV XDG_BIN_HOME="/home/${USER}/.local/bin"
RUN mkdir -p "${XDG_BIN_HOME}"

# Add the user's bin directory to the PATH
ENV PATH="${PATH}:${XDG_BIN_HOME}"

# Install fisher for this user
RUN fish -c "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"

# Install starship for the fish and bash shells 
RUN curl -sS https://starship.rs/install.sh | sh -s -- \
    --yes --bin-dir "${XDG_BIN_HOME}"
# Bash
RUN echo 'eval "$(starship init bash)"' | tee -a "${HOME}/.bashrc"
# Fish
RUN echo 'starship init fish | source' | tee -a "${HOME}/.config/fish/config.fish"

# Hook direnv into the fish and bash shells
# Bash
RUN echo "eval \"$(direnv hook bash)\"" | tee -a "${HOME}/.bashrc"
# Fish
RUN echo 'direnv hook fish | source' | tee -a "${HOME}/.config/fish/config.fish"

# Set the EDITOR variable to use VSCode
ENV EDITOR="code --wait"

# Install Poetry for this user 
RUN pipx install poetry

# Instruct Poetry projects to keep the venv in the project directory
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
