name: Build and Deploy Container

on:
  push:
    branches:
      - "**"
env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login \
            --username "${{ github.actor }}" \
            --password-stdin \
            "${{ env.REGISTRY }}"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install devcontainer
        run: npm install -g @devcontainers/cli

      - name: Build the devcontainer
        run: |
          devcontainer build \
            --workspace-folder . \
            --image-name "${{ env.REGISTRY }}/${{ github.repository }}:0.0.25" \
            --platform linux/amd64 \
            
        env:
          DOCKER_BUILDKIT: 1

      - name: Tag & push the container
        run: |
          echo $(docker images)
